// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbWDOkKXQ2tz-_3fDtik_7_2N8n0GYKI0',
    appId: '1:999167609499:web:0d6abbc84281d1ab54d43e',
    messagingSenderId: '999167609499',
    projectId: 'blog-viewer-82209',
    authDomain: 'blog-viewer-82209.firebaseapp.com',
    storageBucket: 'blog-viewer-82209.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWcYGvYweMc1dp7EvyE_A-Fv0SHvcAmK8',
    appId: '1:999167609499:android:be24548bbda32e5554d43e',
    messagingSenderId: '999167609499',
    projectId: 'blog-viewer-82209',
    storageBucket: 'blog-viewer-82209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsKCs6stCyADWRjxPjAxt5BIwF_bcTNng',
    appId: '1:999167609499:ios:d23003f19675431454d43e',
    messagingSenderId: '999167609499',
    projectId: 'blog-viewer-82209',
    storageBucket: 'blog-viewer-82209.appspot.com',
    iosBundleId: 'com.khaled.blogViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsKCs6stCyADWRjxPjAxt5BIwF_bcTNng',
    appId: '1:999167609499:ios:ddbde3fadbbd788354d43e',
    messagingSenderId: '999167609499',
    projectId: 'blog-viewer-82209',
    storageBucket: 'blog-viewer-82209.appspot.com',
    iosBundleId: 'com.khaled.blogViewer.RunnerTests',
  );
}
